### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by vsd550** [Gastd/p3at_tutorial#1]
Hi!
How can we go about launching the relevant nodes and launch files to achieve the navigation simulation in gazebo.
Please give a walk through the steps.
Your time is highly appreciated
Thanks 
Vijay

**Comment by Gastd** [comment]
Hi @vsd550, to simulate only the robot, you can use the [pioneer3at.gazebo.launch](https://github.com/Gastd/p3at_tutorial/blob/master/launch/pioneer3at.gazebo.launch) to launch the robot in gazebo environment. Also you can bring the navigation stack with this robot, this repo have the config files, alongside with the simulation, in another terminal launch the [amcl_demo.launch](https://github.com/Gastd/p3at_tutorial/blob/master/launch/amcl_demo.launch), this launch file will start the [move_base node](http://wiki.ros.org/move_base) with a [localization node](http://wiki.ros.org/amcl), then you should see the robot moving if you send a 2D Nav Goal through Rviz. This package is based on [husky tutorial](http://wiki.ros.org/husky_navigation/Tutorials/Husky%20AMCL%20Demo)

**Comment by vsd550** [comment]
Hi @Gastd 
The above mentioned steps would simulate and move the robot in gazebo only.
What if we want to do that navigation on the real robot, i.e. achieving a trajectory with obstacle avoidance using data from the sonar array.
Please guide me on that.
Thanks 
Vijay
